version: '3'

vars:
  name: "podium"
  alpinejs_version: "3.13.5"
  htmx_version: "1.9.12"

includes:

  golang:
    taskfile: https://raw.githubusercontent.com/soltiHQ/actions/main/taskfiles/go/Taskfile.yml
    vars:
      image_patch: "-1"

  helpers:
    taskfile: https://raw.githubusercontent.com/soltiHQ/actions/main/taskfiles/helpers/Taskfile.yml

tasks:
  deps:
    desc: Install dependencies.
    cmds:
      - task: helpers:download/file
        vars:
          URL: "https://cdn.jsdelivr.net/npm/alpinejs@{{.alpinejs_version}}/dist/cdn.min.js"
          TO: "ui/static/js/alpine.min.js"
      - task: helpers:download/file
        vars:
          URL: "https://unpkg.com/htmx.org@{{.htmx_version}}/dist/htmx.min.js"
          TO: "ui/static/js/htmx.min.js"

  gen:
    desc: Generate code.
    cmds:
      - task: golang:proto
      - task: golang:templ
      - task: golang:tailwindcss
        vars:
          INPUT: "ui/static/css/app.css"
          OUTPUT: "ui/static/css/tailwindcss.css"

  ci/fumpt:
    desc: Run gofumpt.
    cmds:
      - task: golang:gofumpt

  ci/lint:
    desc: Run golangci-lint.
    cmds:
      - task: golang:golangci

  ci/test:
    desc: Run go test.
    cmds:
      - task: golang:test

  ci/vulnerability:
    desc: Run govulncheck.
    cmds:
      - task: golang:govulncheck

  ci/vendor:
    desc: Prepare project and run 'go mod vendor'.
    cmds:
      - task: deps
      - task: gen
      - task: golang:vendor

  ci/build:
    desc: Build podium binary. Pass GOOS/GOARCH to cross-compile.
    vars:
      GOOS:   '{{.GOOS | default "linux"}}'
      GOARCH: '{{.GOARCH | default "amd64"}}'
    cmds:
      - task: golang:build
        vars:
          NAME: "{{.name}}"
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.GOARCH}}"
