version: '3'

vars:
  git_root:
    sh: git rev-parse --show-toplevel
  go_root:
    sh: go env GOPATH
  go_version:
    sh: grep '^go ' {{.git_root}}/go.mod | awk '{print $2}'
  alpinejs_version: "3.13.5"
  cache_dir: ".cache"
  image_patch: "-1"

tasks:
  default:
    desc: Default task.
    cmds:
      - echo "Please enter a task or use '-l' or '--list-all' to list all available tasks"
    silent: true

  # ================================================#
  # ---------------------INTERNAL-------------------#
  # ================================================#

  _docker/run:
    desc: Internal wrapper to run task in containers.
    internal: true
    silent: true
    requires:
      vars: [ IMAGE, CMD, MOUNT_DIR ]
    dir: "{{.git_root}}"
    cmd: |
      set -euo pipefail
      
      if ! docker image inspect "{{.IMAGE}}" >/dev/null 2>&1; then
        echo "pulling: {{.IMAGE}}"
      
        docker pull -q "{{.IMAGE}}" >/dev/null 2>&1 || {
          echo "Failed to pull image: {{.IMAGE}}"
          exit 1
        }
      fi
      docker run --rm --init --pull=never \
        --security-opt no-new-privileges \
        --user $(id -u):$(id -g) \
        --cap-drop=ALL \
        \
        --volume "{{.git_root}}/{{.MOUNT_DIR}}:/workspace/lighthouse:rw" \
        {{if .VOLUMES}}{{range $vol := .VOLUMES}}--volume {{$vol}} {{end}}{{end}} \
        {{if .ENVS}}{{range $env := .ENVS}}--env "{{$env}}" {{end}}{{end}} \
        \
        --workdir /workspace/lighthouse \
        {{.IMAGE}} \
        {{.CMD}}

  _golang/tool:
    internal: true
    silent: true
    requires: { vars: [ CMD ] }
    cmds:
      - cmd: mkdir -p "{{.git_root}}/{{.cache_dir}}"
      - task: _docker/run
        vars:
          IMAGE: "ghcr.io/soltihq/golang-ci:{{.go_version}}{{.image_patch}}"
          CMD: "{{.CMD}}"
          MOUNT_DIR: "."
          VOLUMES:
            - "{{.git_root}}/{{.cache_dir}}:/tmp/{{.cache_dir}}:rw"
          ENVS:
            - "PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin"
            - "GOTOOLCHAIN=local"
            - "HOME=/tmp/{{.cache_dir}}/home"
            - "XDG_CACHE_HOME=/tmp/{{.cache_dir}}/xdg-cache"
            - "XDG_CONFIG_HOME=/tmp/{{.cache_dir}}/xdg-config"
            - "GOCACHE=/tmp/{{.cache_dir}}/go-build"
            - "GOMODCACHE=/tmp/{{.cache_dir}}/go/pkg/mod"
            - "GOBIN=/usr/local/bin"

  # ================================================#
  # ----------------------PUBLIC--------------------#
  # ================================================#

  alpinejs/download:
    desc: Download alpinejs min
    dir: "{{.git_root}}/ui/js"
    cmds:
      - curl -o alpine.min.js https://cdn.jsdelivr.net/npm/alpinejs@{{.alpinejs_version}}/dist/cdn.min.js
    silent: true

  go/buf:
    desc: Run 'protobuf generate'
    dir: "{{.git_root}}"
    cmds:
      - task: _golang/tool
        vars:
          CMD: "buf generate"
    silent: true

  go/tidy:
    desc: Run 'go mod tidy'
    dir: "{{.git_root}}"
    deps:
      - go/buf
    cmds:
      - task: _golang/tool
        vars:
          CMD: "go mod tidy"
    silent: true

  go/vendor:
    desc: Run 'go mod vendor'
    dir: "{{.git_root}}"
    deps:
      - go/tidy
    cmds:
      - task: _golang/tool
        vars:
          CMD: "go mod vendor"
    silent: true

  go/lint:
    desc: Run 'golangci-lint run'
    dir: "{{.git_root}}"
    deps:
      - go/vendor
    cmds:
      - task: _golang/tool
        vars:
          CMD: "golangci-lint run"
    silent: true

  go/fumpt:
    desc: Run 'fumpt'
    dir: "{{.git_root}}"
    deps:
      - go/vendor
    cmds:
      - task: _golang/tool
        vars:
          CMD: "gofumpt -l -w $(git ls-files \"*.go\")"
    silent: true

  go/test:
    desc: Run tests
    dir: "{{ .git_root }}"
    deps:
      - go/vendor
    cmds:
      - task: _golang/tool
        vars:
          CMD: "go test ./..."
    silent: true

  # ================================================#
  # ----------------------MANUAL--------------------#
  # ================================================#

  go/clean:
    desc: "Run 'go clean -modcache'"
    dir: "{{.git_root}}"
    cmds:
      - 'GOMODCACHE="$PWD/.cache/go/pkg/mod" go clean -modcache'
    silent: true