version: '3'

vars:
  git_root:
    sh: git rev-parse --show-toplevel
  go_root:
    sh: go env GOPATH
  go_version:
    sh: grep '^go ' {{.git_root}}/go.mod | awk '{print $2}'
  go_image_patch: "2"
  go_image: "ghcr.io/soltihq/golang-ci:{{.go_version}}-{{.go_image_patch}}"
  cache_dir: ".cache"

includes:
  isolation:
    taskfile: ./.tasks/isolation.yaml
    dir: "{{.git_root}}"

  go:
    taskfile: ./.tasks/golang.yaml
    dir: "{{.git_root}}"

tasks:
  default:
    cmds:
      - task --list