inputs:
  toolchain_tag:
    description: e.g. golang-ci image tag (go_version + patch)
    required: true

outputs:
  cache-hit:
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Prepare cache dirs
      shell: bash
      run: mkdir -p .cache/mod .cache/build .cache/buf .cache/golangci-lint

    - name: Restore cache
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: .cache
        key: cache-${{ runner.os }}-${{ runner.arch }}-${{ inputs.toolchain_tag }}-${{ hashFiles('go.sum') }}
        restore-keys: |
          cache-${{ runner.os }}-${{ runner.arch }}-${{ inputs.toolchain_tag }}-
