name: Build

on:
  workflow_call: {}

jobs:
  build:
    runs-on: ${{ vars.RUNS_ON }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Get Cache
        id: cache_get
        uses: soltiHQ/actions/cache-get@main
        with:
          paths: |
            .cache
            vendor
            api/gen
            ui/static
            ui/templates
          key: podium-${{ hashFiles('go.mod', 'go.sum', 'Taskfile.yaml') }}

      - name: Build ${{ matrix.goos }}/${{ matrix.goarch }}
        uses: soltiHQ/actions/taskfile@main
        with:
          command: ci/build GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }}

      - name: Put Cache
        if: steps.cache_get.outputs.cache-hit != 'true'
        uses: soltiHQ/actions/cache-put@main
        with:
          paths: |
            .cache
            vendor
            api/gen
            ui/static
            ui/templates
          key: podium-${{ hashFiles('go.mod', 'go.sum', 'Taskfile.yaml') }}
