name: Checks

on:
  workflow_call: {}

jobs:
  vendor:
    name: Vendor
    uses: ./.github/workflows/.vendor.yml

  check:
    runs-on: ${{ vars.RUNS_ON }}
    needs: vendor
    strategy:
      fail-fast: false
      matrix:
        command:
          - ci/fumpt
          - ci/vulnerability
          - ci/lint
          - ci/test
    steps:
      - uses: actions/checkout@v4

      - name: Get Cache
        id: cache_get
        uses: soltiHQ/actions/cache-get@main
        with:
          paths: |
            .cache
            vendor
            api/gen
            ui/static/js/alpine.min.js
            ui/static/js/htmx.min.js
            ui/static/css/tailwindcss.css
            ui/templates/**/*_templ.go
          key: podium-${{ hashFiles('go.mod', 'go.sum', 'Taskfile.yaml') }}

      - name: Run ${{ matrix.command }}
        uses: soltiHQ/actions/taskfile@main
        with:
          command: ${{ matrix.command }}

      - name: Put Cache
        if: steps.cache_get.outputs.cache-hit != 'true'
        uses: soltiHQ/actions/cache-put@main
        with:
          paths: |
            .cache
            vendor
            api/gen
            ui/static/js/alpine.min.js
            ui/static/js/htmx.min.js
            ui/static/css/tailwindcss.css
            ui/templates/**/*_templ.go
          key: podium-${{ hashFiles('go.mod', 'go.sum', 'Taskfile.yaml') }}
